version: '3.8'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-openspecimen-web:
    image: bibbox/openspecimen:v6-3-x
    container_name: §§INSTANCE-openspecimen
    command: --lower_case_table_names=1
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-openspecimen-db:openspecimen-db
    ports:
      - "8065:8080"
    environment:
      - DATABASE_HOST=openspecimen-db
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
      - TOMCAT_MANAGER_USER=TOMCAT_MANAGER_USER
      - TOMCAT_MANAGER_PASSWORD=TOMCAT_MANAGER_PASSWORD
      - INSTITUTE_NAME=INSTITUTE_NAME
      - EMAIL_ADRESS=EMAIL_ADRESS
      - FIRST_NAME=FIRST_NAME
      - LAST_NAME=LAST_NAME
      - LOGIN_NAME=LOGIN_NAME
      - ADRESS=ADRESS
    depends_on:
      - §§INSTANCE-openspecimen-db
    volumes: 
      - ./images/openspecimen/configs/openspecimen.cnf:/etc/mysql/conf.d/openspecimen.cnf:ro #read only
      - ./data/os-data:/var/lib/openspecimen/data
      - ./data/os-plugins:/var/lib/openspecimen/plugins

  §§INSTANCE-openspecimen-db:
    image: mysql:5.7
    container_name: §§INSTANCE-openspecimen-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
    volumes:
      - ./data/mysql:/var/lib/mysql
