version: '3.8'

networks:
    bibbox-default-network:
      external: true

services:

  bibbox-openspecimen-web:
    image: bibbox/openspecimen:v6-3-x
    container_name: bibbox-openspecimen-web_tng
    command: --lower_case_table_names=1
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - bibbox-openspecimen-db:openspecimen-db
    ports:
      - "8090:8080"
    environment:
      - DATABASE_HOST=openspecimen-db
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
      - TOMCAT_MANAGER_USER=v
      - TOMCAT_MANAGER_PASSWORD=vendetta
      - INSTITUTE_NAME=MUG
      - EMAIL_ADRESS=vi
      - FIRST_NAME=Stefan
      - LAST_NAME=Herdy
      - LOGIN_NAME=herdys
      - ADRESS=Stiftingtalstraße
    depends_on:
      - bibbox-openspecimen-db
    volumes:
      - ./images/openspecimen/configs/openspecimen.cnf:/etc/mysql/conf.d/openspecimen.cnf:ro
      - ./data/os-data:/var/lib/openspecimen/data
      - ./data/os-plugins:/var/lib/openspecimen/plugins
    env_file: 
      - params.env

  bibbox-openspecimen-db:
    image: mysql:5.7
    container_name: bibbox-openspecimen-db_tng
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./images/openspecimen/configs/openspecimen.cnf:/etc/mysql/conf.d/openspecimen.cnf
    env_file:
      - params.env

#  §§INSTANCE-openspecimen-data:
#    image: busybox
#    container_name: §§INSTANCE-openspecimen-data
#    volumes:
#      - ./images/openspecimen/configs/openspecimen.cnf:/etc/mysql/conf.d/openspecimen.cnf:ro #read only
#      - ./data/os-data:/var/lib/openspecimen/data
#      - ./data/os-plugins:/var/lib/openspecimen/plugins
#      - ./data/mysql:/var/lib/mysql
